DATASET_2A_PATH = "/Users/hetvigandhi/Desktop/BCICIV_2a_gdf"  # ← CHANGE THIS
DATASET_2B_PATH = "/Users/hetvigandhi/Desktop/BCICIV_2b_gdf"  # ← CHANGE THIS

# Don't change anything below this line
SAMPLING_RATE = 250
LOWCUT = 8
HIGHCUT = 30
EPOCH_START = 0.5
EPOCH_END = 2.5
DATASET_2A_CHANNELS = 22
DATASET_2A_CLASSES = 4
DATASET_2B_CHANNELS = 3
DATASET_2B_CLASSES = 2
VALIDATION_SPLIT = 0.2
RANDOM_SEED = 42